<script>
  import { ZoomableContainer, Breadcrumbs } from 'svelte-zoomable@0.0.5';
  import ZoomGridItems from './ZoomGridItems.svelte';

  // Data generated by faker.js
  const companies = [
    'Lueilwitz - Gutmann',
    'Okuneva - Dare',
    'Halvorson and Sons',
    'VonRueden Inc',
    'Ebert LLC',
    'Aufderhar and Sons',
    'Bartoletti - Gibson',
    'Torphy Inc',
    'Muller Group',
    'Mertz - Kutch',
    'Wisoky, Bogisich and Kerluke',
    'Treutel, Connelly and Legros',
    "Harber, Konopelski and D'Amore",
    'Davis, Reilly and Zemlak',
    'Harber - Walter',
    'Reilly - Vandervort',
    'Jast LLC',
    'Howe Group',
    'Emard and Sons',
    'Hayes Group',
    'Rutherford, Ward and Terry',
    'Marvin, Emard and Botsford',
    'Okuneva - Macejkovic',
    'Tremblay, Hegmann and Rice',
    'Hegmann - Rowe',
    'Barrows - Labadie',
    'Jacobson, Hackett and Hahn',
    'Kreiger - Zemlak',
    "Bednar, Bartoletti and O'Conner",
    'Wiza LLC',
  ];

  const countries = [
    'Syrian Arab Republic',
    'Fiji',
    'Uzbekistan',
    'Isle of Man',
    'Dominican Republic',
    'Gibraltar',
    'Cape Verde',
    'Antigua and Barbuda',
    'Guatemala',
    'Reunion',
    'Chad',
    'Hungary',
    'Malaysia',
    'Djibouti',
    'Belgium',
    'New Zealand',
    'Virgin Islands, U.S.',
    'Guatemala',
    'Belgium',
    'Denmark',
    'Israel',
    'Austria',
    'Georgia',
    'Niger',
    'Comoros',
    'Samoa',
    'Micronesia',
    'Tajikistan',
    'Maldives',
    'Austria',
  ];

  const names = [
    'Annette Bergnaum',
    'Molly Hauck',
    "Roberta O'Conner Sr.",
    'Lucy Huels III',
    'Mr. Matthew Grady',
    'Gordon Schulist',
    'Miss Patsy Bayer',
    'Pete Fisher',
    'Salvatore Ernser',
    'Bert Dibbert',
    'Eddie Hackett',
    'Blanche Lehner',
    'Katrina Crooks',
    'Erma Marks',
    'Tami Reichel',
    'Tommie Considine DVM',
    'Raymond Howell',
    'Roland Fritsch',
    'Melvin Rolfson',
    'Vicky Langworth',
    'Lloyd Beatty',
    'Eula Bosco',
    'Bobbie Heathcote V',
    'Johnnie Trantow',
    'Dixie Wolf',
    'Vera Kunde',
    'Ms. Patrick Zulauf',
    'Angela Commerata',
    'Anthony Dibbert',
    'Scott Larkin',
  ];

  const lorem = [
    'Et vel odio tempore animi dolorum ut error. Perspiciatis et doloremque aut laudantium qui harum voluptas qui ad. Ea sit qui corrupti suscipit placeat sunt officia.',
    'Quae neque blanditiis voluptates eum vero. Qui ipsa est dolorem ut ut. Itaque ut voluptatem et voluptatem ratione. Fuga vero sint optio dolorem tempore sunt ea nemo quidem. Ratione quia mollitia quisquam nemo vitae.',
    'Et possimus perspiciatis repudiandae ex. Distinctio iure aperiam nihil sunt in accusamus. Voluptatem quod libero reiciendis sunt ad repudiandae consectetur omnis sit.',
    'Officia dicta deleniti et perferendis placeat sed fuga rem. Labore est cum debitis repellendus voluptatem voluptate rem. Libero est est.',
    'Quasi tempora sit vitae ipsam iusto nulla suscipit et. In dolor occaecati voluptatem non totam quod sapiente voluptas. Qui enim occaecati. Tempora facere aliquam tempora. Iste maxime qui commodi sed. Eius ut dolorem perspiciatis assumenda ex.',
    'Natus ad dicta excepturi eos cupiditate. Ipsum laborum omnis. Quidem ipsum quae minus nulla nulla tempore. Temporibus ut maiores est quisquam vel rem delectus. Illum nesciunt eveniet commodi est accusamus. Ab eum eaque.',
    'Eos accusamus est est eos excepturi suscipit dolorem cum. Ullam fugiat minus et. Quo soluta rerum architecto et enim. Rerum autem eum quo et. Reiciendis voluptatibus adipisci tempore quia iusto eius.',
    'Ut incidunt quasi magnam molestiae facilis quae. Fugiat porro excepturi et maiores quia. Possimus maiores nostrum ut consectetur saepe error qui assumenda sed.',
  ];

  export let zoomPreset;
  let zoomManager;

  const minItems = 5;
  const maxItems = 12;
  function getNum() {
    return Math.round(Math.random() * (maxItems - minItems)) + minItems;
  }

  function getItem(list) {
    return list[Math.floor(Math.random() * list.length)];
  }

  let items = Array.from({ length: getNum() }, (_, i0) => {
    return {
      id: i0,
      name: getItem(companies),
      children: Array.from({ length: getNum() }, (_, i1) => {
        return {
          id: i1,
          name: getItem(countries),
          children: Array.from({ length: getNum() }, (_, i2) => {
            return {
              id: i2,
              name: getItem(names),
              text: getItem(lorem),
            };
          }),
        };
      }),
    };
  });
</script>

<h3 id="title">
  <Breadcrumbs {zoomManager} />
</h3>

<section>
  <ZoomableContainer bind:zoomManager transitionPreset={zoomPreset}>
    <ZoomGridItems {items} />
  </ZoomableContainer>
</section>

<style>
  section {
    border: solid 1px lightgray;
    width: 23rem;
    height: 32rem;
    padding: 1rem;
  }
</style>
