# The Logseq directory to open.
data = "/Users/dimfeld/logseq"

# Write the rendered pages into this directory
output = "pkm-pages"

script = "export-logseq-notes.rhai"

# Use this template when rendering pages. See the `templates` directory for examples.
template = "export-logseq-notes.tmpl"

# Use this file extension on the rendered pages
extension = "html"

# When performing syntax highlighting, prefix the classes with
# this string. This is optional.
highlight_class_prefix = "sy-"


##### Tags Output ####

# Use this attribute to gather tags for a page, which can be used in the
# template to populate front matter for a CMS
tags_attr = "tags"

# Use all hashtags in a page when gathering tags, not just values of the tags_attr
use_all_hashtags = true

# When gathering tags for a page template, ignore these tags
# For example, your book note pages may have lines like this:
# Tags:: #Books #[[In Progress]] #Finance
# So you can add "Books" and "In Progress" here to prevent them from
# being listed as tags for a page and cluttering up the tags.
omit_attributes = [
  "Articles",
  "Inbox",
  "In Progress",
  "Newsletter Item",
  "Done",
  "Readwise",
  "Deliberate Practice",
  "Video",
  "note-export",
  "public",
  "progress",
  "Progress",
  "tags",
  "Tags",
  "wrap-el",
  "content-el",
  "wrap-class"
]



##### Link Handling #####

# If a block contains only tags and nothing else, don't render
# any of the tags that reference unexported pages.
filter_link_only_blocks = true

# When rendering links, use this URL prefix (optional)
base_url = "/notes"

# HTML classes for various elements
class_bold = "font-bold"
class_italic = "italic"
class_strikethrough = "line-through"
class_highlight = "bg-yellow-200"
class_blockquote = ""
class_hr = ""
class_block_embed = ""
class_page_embed_container = ""
class_page_embed_title = ""
class_page_embed_content = ""
class_attr_name = "font-medium text-gray-800"
class_attr_value = ""

# Convert -- to &emdash;
convert_emdash = true

##### Upcoming features #####

# Write namespaced pages into nested directories.
# A page with the title Books/Notes/A Book
# would be written to books/notes/a_book
# When false (the default), it will be
# written to books_notes_a_book.
namespace_dirs = false

[pic_store]
url = "http://localhost:7205"
upload_profile = "blog"
